server:
  port: 8088
spring:
  application:
    name: "cue-event-manager-file-service"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        format_sql: true
        show_sql: true
flyway:
  enabled: true
  locations: "classpath:db/migration"
  baseline-on-migrate: true
  driver-class-name: "com.mysql.cj.jdbc.Driver"
app:
  internal:
    secret: "${INTERNAL_SECRET:123}"
eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URL:http://localhost:8761/eureka}"
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  aws:
    s3:
      bucketName: ${AWS_S3_BUCKET_NAME}
      region: ${AWS_REGION}
